[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."analyze"]
  timeout = 26

[functions."analyze".environment]
  NODE_OPTIONS = "--max-old-space-size=1024"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
